### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ghifar1** [sonodima/cw_betterlobby#1]
![image](https://github.com/sonodima/cw-betterlobby/assets/38382464/208df425-eccd-4e3b-8f8f-d9ac3a72c2e0)

**Comment by ghifar1** [comment]
Stack trace:
SurfaceNetworkHandler.RPCA_OpenDoor () (at <c561fa8d81824a1aa363bc42554b44c5>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <787acc3c9a4c471ba7d971300105af24>:0)
Photon.Pun.PhotonNetwork.ExecuteRpc (ExitGames.Client.Photon.Hashtable rpcData, Photon.Realtime.Player sender) (at <59bd67b150014430a4f68bfc682d0aae>:0)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, Photon.Realtime.Player player, System.Boolean encrypt, System.Object[] parameters) (at <59bd67b150014430a4f68bfc682d0aae>:0)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, System.Boolean encrypt, System.Object[] parameters) (at <59bd67b150014430a4f68bfc682d0aae>:0)
Photon.Pun.PhotonView.RPC (System.String methodName, Photon.Pun.RpcTarget target, System.Object[] parameters) (at <59bd67b150014430a4f68bfc682d0aae>:0)
BetterLobby.Plugin+<OnPlayerJoined>d__7.MoveNext () (at <9257ba4a5ad6499eaeba5c278ee9cff8>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <801ef9485ea54ad392ab1752511dc748>:0)

**Comment by sonodima** [comment]
Thank you, fixed this in 1.2.1!

**Comment by ghifari-ti** [comment]
> Thank you, fixed this in 1.2.1!

Thanks
