### ISSUE TITLE
Fill Lobby doesn't work after update

### ISSUE THREAD

**Issue by JamesBong0070** [sonodima/cw_betterlobby#2]
:)

**Comment by sonodima** [comment]
Thank you for the report. I have been looking into this for, but I am still unsure on what they actually changed.

The vanillaCompatible attribute has been added with the last commit, but it does not seem to fix the problem.

**Comment by sonodima** [comment]
Okay, I think I have it working again. Please test 1.2.0 and let me know.

**Comment by JamesBong0070** [comment]
Yup, it is working now. Thanks!

**Comment by JamesBong0070** [comment]
Yup, it's working now. Thanks!
