### ISSUE TITLE
Inviting friends through the ESC menu & invite pod puts uncloseable window

### ISSUE THREAD

**Issue by Ruikio** [sonodima/cw_betterlobby#3]
![image](https://github.com/sonodima/cw-betterlobby/assets/42963569/cafb353e-8fe2-4b7e-8923-479702155b55)

I'm unable to close the screen :( Forces a restart.

**Comment by sonodima** [comment]
Unfortunately this is an issue with the game, and not this mod

If I recall correctly, switching rendering modes (fullscreen to windowed and vice-versa) when the overlay gets stuck should fix the issue, but you will have to try and navigate the menu without clearly seeing it :(
